name: miguel_marin_training
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.13.3
  equatable: ^2.0.5
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  intl: any
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo.png'

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - .env
